homeassistant:
  # Name of the location where Home Assistant is running
  name: "Villa Villerkulla"
  # Location required to calculate the time the sun rises and sets
  latitude: 59.8585
  longitude: 17.6454
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
  - yamaha
  - sonos

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Philips Hue
hue:
  bridges:
    - host: 192.168.1.77
  
# Track the sun
sun:

input_number:
  tvroom_brightness:
    name: "TVroom Brightness"
    initial: 150
    min: 0
    max: 255
    step: 15
  dressingroom_brightness:
    name: "Dressingroom Brightness"
    initial: 150
    min: 0
    max: 255
    step: 15
  tvroom_manual_on:
    name: "TVroom manually set"
    initial: 0
    min: 0
    max: 1
    step: 1
  dressingroom_manual_on:
    name: "Dressingroom manually set"
    initial: 0
    min: 0
    max: 1
    step: 1
    
# Weather prediction
sensor:
  - platform: hue_sensor
  - platform: yr
  - platform: template
    sensors:
      current_activity:
        friendly_name: "Current Activity"
        value_template: '{{ states.remote.harmony.attributes.current_activity }}'
      tvroom_lux:
        friendly_name: "Ljus 1"
        entity_id: sensor.motion_tvroom
        unit_of_measurement: "lux"
        value_template: "{{ states.sensor.motion_tvroom.attributes.lux }}"
      dressingroom_lux:
        friendly_name: "Ljus 2"
        entity_id: sensor.motion_dressingroom
        unit_of_measurement: "lux"
        value_template: "{{ states.sensor.motion_dressingroom.attributes.lux }}"
      tvroom_hours:
        value_template: >
          {% if is_state("input_number.tvroom_manual_on", "1.0") %}
          1
          {% else %}
          0
          {% endif %}          
      dressingroom_hours:
        value_template: >
          {% if is_state("input_number.dressingroom_manual_on", "1.0") %}
          1
          {% else %}
          0
          {% endif %}
      dressingroom_minutes:
        value_template: >
          {% if now().hour < 6 %}
          0
          {% elif now().hour < 8 %}
          3
          {% elif now().hour < 10 %}
          15
          {% else %}
          0
          {% endif %}

python_script:

remote:
  - platform: harmony
    name: Harmony 
    host: 192.168.1.73


#emulated_hue:
#  host_ip: 192.168.1.202
#  listen_port: 8300
#  exposed_domains:
#    - light
#    - scene
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
