homeassistant:
  # Name of the location where Home Assistant is running
  name: "Villa Villerkulla"
  # Location required to calculate the time the sun rises and sets
  latitude: 59.8585
  longitude: 17.6454
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
  - yamaha
  - sonos

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  purge_interval: 1
  purge_keep_days: 5

# View all events in a logbook
logbook:

# Philips Hue
hue:
  bridges:
    - host: 192.168.1.77
  
# Track the sun
sun:

mqtt:
  broker: 192.168.1.202
  username: "HomeAssistant"
  password: "BurkGurk"

switch:
  - platform: mqtt
    name: "sonoff-0502"
    state_topic: "stat/sonoff_0502/POWER"
    command_topic: "cmnd/sonoff_0502/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "sonoff-4995"
    state_topic: "stat/sonoff_4995/POWER"
    command_topic: "cmnd/sonoff_4995/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  
input_number:
  tvroom_brightness:
    name: "TVroom Brightness"
    initial: 150
    min: 0
    max: 255
    step: 15
  dressingroom_brightness:
    name: "Dressingroom Brightness"
    initial: 150
    min: 0
    max: 255
    step: 15
  tvroom_manual_on:
    name: "TVroom manually set"
    initial: 0
    min: 0
    max: 1
    step: 1
  dressingroom_manual_on:
    name: "Dressingroom manually set"
    initial: 0
    min: 0
    max: 1
    step: 1
    
# Weather prediction
sensor:
  - platform: hue
    ip_address: 192.168.1.77
    token: zMHZEypUOcxwO3TSp1ed-ZL3e1jmWVgAJsdENlgs
  - platform: yr
  - platform: template
    sensors:
      current_activity:
        friendly_name: "Current Activity"
        value_template: '{{ states.remote.harmony.attributes.current_activity }}'
      tvroom_lux:
        friendly_name: "Ljus 1"
        unit_of_measurement: "lux"
        value_template: "{{ states.sensor.motion_tvroom.attributes.lux }}"
      dressingroom_lux:
        friendly_name: "Ljus 2"
        unit_of_measurement: "lux"
        value_template: "{{ states.sensor.motion_dressingroom.attributes.lux }}"
      tvroom_hours:
        value_template: >
          {% if is_state("input_number.tvroom_manual_on", "1.0") %}
          1
          {% else %}
          0
          {% endif %}          
      dressingroom_hours:
        value_template: >
          {% if is_state("input_number.dressingroom_manual_on", "1.0") %}
          1
          {% else %}
          0
          {% endif %}
      dressingroom_minutes:
        value_template: >
          {% if now().hour < 6 %}
          0
          {% elif now().hour < 8 %}
          3
          {% elif now().hour < 10 %}
          15
          {% else %}
          0
          {% endif %}
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'


python_script:

remote:
  - platform: harmony
    name: Harmony 
    host: 192.168.1.73

scene:
  - name: "Reading light"
    entities:
      group.kitchen_table:
        state: on
        brightness: 255
        color_temp: 249
  - name: "Cozy"
    entities:
      group.kitchen_table:
        state: on
        brightness: 80
        color_temp: 458
  - name: "Morning"
    entities:
      group.kitchen_table:
        state: on
        brightness: 25
        color_temp: 458
  - name: "Windows Off"
    entities:
      light.living_room_window_1:
        state: off
      light.living_room_window_2:
        state: off
      light.living_room_window_3:
        state: off
  - name: "Windows On"
    entities:
      light.living_room_window_1:
        state: on
        brightness: 180
      light.living_room_window_2:
        state: on
        brightness: 180
      light.living_room_window_3:
        state: on
        brightness: 180
  - name: "Stairs Off"
    entities:
      light.stairs_1:
        state: off
      light.stairs_2:
        state: off
  - name: "Stairs On"
    entities:
      light.stairs_1:
        state: on
        brightness: 128
      light.stairs_2:
        state: on
        brightness: 128
  
emulated_hue:
  expose_by_default: false
  entities:
    light.h_stairs:
      name: "stairs"
      hidden: false 
    light.living_room:
      name: "living room window"
      hidden: false 
    light.t_mancave:
      name: "mancave"
      hidden: false 
    light.h_kitchen:
      name: "ceiling"
      hidden: false 
    light.h_dressing_room:
      name: "dressing room"
      hidden: false 
    light.h_tv_room:
      name: "tv room"
      hidden: false 
    scene.cozy:
      hidden: false
    scene.reading_light:
      hidden: false
    scene.morning:
      hidden: false

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
